### ISSUE TITLE
Windows Deprecation Error

### ISSUE THREAD

**Issue by tbrowning** [matteocrippa/iracing-replay-video#12]
Seems to still be running okay on Mac / Linux, but Windows is throwing an error ("fastest.forEach is not a function" or something like that.)

Not sure if you're still working on this, just FYI. :)

**Comment by matteocrippa** [comment]
Sadly I have no a win pc with nodejs running, but if you want feel free to copy paste the error so I can investigate on that @tbrowning

**Comment by tbrowning** [comment]
$ yarn run all
yarn run v1.6.0
$ yarn run data && yarn run images && yarn run video
$ node ./scripts/prepare.js
🚗  - Generated driver list
🛣  - Generated track info
D:\Program Files (x86)\Replay Overlay\lib\generator.js:114
  fastest.forEach(function (f) {
            ^

TypeError: fastest.forEach is not a function
    at populateFastestLap (D:\Program Files (x86)\Replay Overlay\lib\generator.js:114:11)
    at Object.exports.generateLeaderBoards (D:\Program Files (x86)\Newer Replay
Thing\lib\generator.js:57:14)
    at Object.<anonymous> (D:\Program Files (x86)\Replay Overlay\scripts\prepare.js:56:28)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by matteocrippa** [comment]
@tbrowning it should be fixed now, I also improved the way it slices the videos and apply the overlay, it should be faster now even for long videos.

I'm testing right now with a 40min endurance and it seems quite fast.
